        $(document).ready(function(){
            $('.open-nav').click(function(){
                $('.menu').toggleClass('active');
                $('.open-menu').toggleClass('open');
            });
        });
        function myFunction(x) {
            x.classList.toggle("change");
          }
        

        //alterar lista de ganhos ao clicar button
        var h4 = document.getElementById('basicoValor');
        var hh4 = document.getElementById('medioValor');
        var hhh4 = document.getElementById('avancadoValor');
        
        var Basico1 = document.getElementById('Basico1');
        var Basico2 = document.getElementById('Basico2');
        var Basico3 = document.getElementById('Basico3');
        var Basico4 = document.getElementById('Basico4');

        var medio1 = document.getElementById('medio1');
        var medio2 = document.getElementById('medio2');
        var medio3 = document.getElementById('medio3');
        var medio4 = document.getElementById('medio4');
        var medio5 = document.getElementById('medio5');
        var medio6 = document.getElementById('medio6');
        var medio7 = document.getElementById('medio7');
        var medio8 = document.getElementById('medio8');

        var avancado1 = document.getElementById('avancado1');
        var avancado2 = document.getElementById('avancado2');
        var avancado3 = document.getElementById('avancado3');
        var avancado4 = document.getElementById('avancado4');
        var avancado5 = document.getElementById('avancado5');
        var avancado6 = document.getElementById('avancado6');
        var avancado7 = document.getElementById('avancado7');
        var avancado8 = document.getElementById('avancado8');


    function botao_clicado2(botao) {

        h4.innerText = 'R$87';
        hh4.innerText = 'R$187';
        hhh4.innerText = 'R$287';


        Basico1.innerText = 'Área VIP';
        Basico2.innerText = 'Sorteio PIX - R$100 (Mensalmente)';
        Basico3.innerText = 'Mimos';
        Basico4.innerText = 'Pague por 1KG de Açaí e leve +1KG grátis (Mensalmente)';
        Basico5.innerText = 'Você tem 5% de desconto nos produtos de uma loja Física Façaí';
        Basico6.innerText = '4 porções de 5 opções de acompanhamentos (Mensalmente)';
        Basico7.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        Basico8.innerText = 'Área de membros';
        Basico9.innerText = 'Eventos Exclusivos';
        Basico10.innerText = 'Sorteios de Viagem de Fim de Ano';
        Basico11.innerText = 'Caixas Temáticas';

        medio1.innerText = 'Área VIP';
        medio2.innerText = 'Sorteio PIX - R$150 (Mensalmente)';
        medio3.innerText = 'Mimos';
        medio4.innerText = 'Pague por 3KG de Açaí e leve +3KG grátis (Mensalmente)';
        medio5.innerText = 'Você tem 10% de desconto nos produtos de uma loja Física Façaí';
        medio6.innerText = '4 porções de 10 opções de acompanhamentos (Mensalmente)';
        medio7.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        medio8.innerText = 'Área de membros';
        medio9.innerText = 'Eventos Exclusivos';
        medio10.innerText = 'Sorteios de Viagem de Fim de Ano';
        medio11.innerText = 'Caixas Temáticas';


        avancado1.innerText = 'Área VIP';
        avancado2.innerText = 'Sorteio PIX - R$200 (Mensalmente)';
        avancado3.innerText = 'Mimos';
        avancado4.innerText = 'Pague por 5KG de Açaí e leve +5KG grátis (Mensalmente)';
        avancado5.innerText = 'Você tem 21% de desconto nos produtos de uma loja Física Façaí';
        avancado6.innerText = '4 porções de 20 opções de acompanhamentos (Mensalmente)';
        avancado7.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        avancado8.innerText = 'Área de membros';
        avancado9.innerText = 'Eventos Exclusivos';
        avancado10.innerText = 'Sorteios de Viagem de Fim de Ano';
        avancado11.innerText = 'Caixas Temáticas';


        
    }

    function botao_clicado3(botao) {

        h4.innerText = 'R$67';
        hh4.innerText = 'R$167';
        hhh4.innerText = 'R$275';

        Basico1.innerText = 'Área VIP';
        Basico2.innerText = 'Sorteio PIX - R$100 (Mensalmente)';
        Basico3.innerText = 'Mimos';
        Basico4.innerText = 'Pague por 1KG de Açaí e leve +1KG grátis (Mensalmente)';
        Basico5.innerText = 'Você tem 5% de desconto nos produtos de uma loja Física Façaí';
        Basico6.innerText = '4 porções de 5 opções de acompanhamentos (Mensalmente)';
        Basico7.innerText = 'Eventos Exclusivos';
        Basico8.innerText = 'Sorteio de Viagem de Fim de Ano (Gramado - RS)';
        Basico9.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        Basico10.innerText = 'Área de membros';
        Basico11.innerText = 'Caixas Temáticas';

        medio1.innerText = 'Área VIP';
        medio2.innerText = 'Sorteio PIX - R$150 (Mensalmente)';
        medio3.innerText = 'Mimos';
        medio4.innerText = 'Pague por 3KG de Açaí e leve +3KG grátis (Mensalmente)';
        medio5.innerText = 'Você tem 10% de desconto nos produtos de uma loja Física Façaí';
        medio6.innerText = '4 porções de 10 opções de acompanhamentos (Mensalmente)';
        medio7.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        medio8.innerText = 'Eventos Exclusivos';
        medio9.innerText = 'Sorteio de Viagem de Fim de Ano (Fernando de Noronha - PE)';
        medio10.innerText = '2 caixas Temáticas';
        medio11.innerText = 'Área de membros';

        avancado1.innerText = 'Área VIP';
        avancado2.innerText = 'Sorteio PIX - R$200 (Mensalmente)';
        avancado3.innerText = 'Mimos';
        avancado4.innerText = 'Pague por 5KG de Açaí e leve +5KG grátis (Mensalmente)';
        avancado5.innerText = 'Você tem 21% de desconto nos produtos de uma loja Física Façaí';
        avancado6.innerText = '4 porções de 20 opções de acompanhamentos (Mensalmente)';
        avancado7.innerText = 'Acesso a um serviço de Streaming (Netflix, Disney+, Telecine, Spotify, Amazon Prime ou Globo Play)';
        avancado8.innerText = 'Área de membros';
        avancado9.innerText = 'Eventos Exclusivos';
        avancado10.innerText = 'Sorteio de Viagem de Fim de Ano (Buenos Aires - Argentina)';
        avancado11.innerText = '3 caixas Temáticas';
    }



//faq
    var faq1 = document.getElementById("faq-box1")
    var faq2 = document.getElementById("faq-box2")
    var faq3 = document.getElementById("faq-box3")
    var faq4 = document.getElementById("faq-box4")
    var faq5 = document.getElementById("faq-box5")
    var faq6 = document.getElementById("faq-box6")

    var duvida1 = document.getElementById("duvida1")
    var duvida2 = document.getElementById("duvida2")
    var duvida3 = document.getElementById("duvida3")
    var duvida4 = document.getElementById("duvida4")
    var duvida5 = document.getElementById("duvida5")
    var duvida6 = document.getElementById("duvida6")



    faq1.addEventListener("click", function(){

        if(duvida1.style.display === "block") {
            duvida1.style.display = "none";
        } else {
            duvida1.style.display= "block"
        }
    })

    faq2.addEventListener("click", function(){

        if(duvida2.style.display === "block") {
            duvida2.style.display = "none";
        } else {
            duvida2.style.display= "block"
        }
    })

    faq3.addEventListener("click", function(){

        if(duvida3.style.display === "block") {
            duvida3.style.display = "none";
        } else {
            duvida3.style.display= "block"
        }
    })
    faq4.addEventListener("click", function(){

        if(duvida4.style.display === "block") {
            duvida4.style.display = "none";
        } else {
            duvida4.style.display= "block"
        }
    })
    faq5.addEventListener("click", function(){

        if(duvida5.style.display === "block") {
            duvida5.style.display = "none";
        } else {
            duvida5.style.display= "block"
        }
    })
    faq6.addEventListener("click", function(){

        if(duvida6.style.display === "block") {
            duvida6.style.display = "none";
        } else {
            duvida6.style.display= "block"
        }
    })

